require('dotenv').config();
const { ethers, network } = require("hardhat");
const fs   = require("fs");
const path = require("path");

async function main() {
  const GasScheduler = await ethers.getContractFactory("GasOptimizedScheduler");
  console.log(`\nDeploying GasOptimizedScheduler to ${network.name}…`);

  const contract = await GasScheduler.deploy();
  await contract.waitForDeployment();

  const address     = await contract.getAddress();
  const deployedAt  = new Date().toISOString();

  console.log(`✅ Contract deployed to: ${address}`);
  console.log(`   Network : ${network.name}`);
  console.log(`   Time    : ${deployedAt}`);

  // ── Write deployed.json so keeper + frontend can auto-load it ──────────
  const outPath = path.join(__dirname, '..', 'deployed.json');
  fs.writeFileSync(outPath, JSON.stringify({
    note:       "Auto-generated by scripts/deploy.cjs — do not edit manually.",
    network:    network.name,
    address,
    deployedAt,
  }, null, 2));
  console.log(`   Saved  → deployed.json`);

  // ── Print the Etherscan link if on Sepolia ─────────────────────────────
  if (network.name === 'sepolia') {
    console.log(`   Explorer: https://sepolia.etherscan.io/address/${address}`);
  }

  console.log('\n👉 Paste this address into the GasGuard UI or run the keeper:\n');
  console.log(`   CONTRACT_ADDRESS=${address}\n`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});