/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GasOptimizedScheduler {
  export type ScheduledTxStruct = {
    recipient: AddressLike;
    amount: BigNumberish;
    maxGasPrice: BigNumberish;
    expiry: BigNumberish;
    owner: AddressLike;
    executed: boolean;
    cancelled: boolean;
  };

  export type ScheduledTxStructOutput = [
    recipient: string,
    amount: bigint,
    maxGasPrice: bigint,
    expiry: bigint,
    owner: string,
    executed: boolean,
    cancelled: boolean
  ] & {
    recipient: string;
    amount: bigint;
    maxGasPrice: bigint;
    expiry: bigint;
    owner: string;
    executed: boolean;
    cancelled: boolean;
  };
}

export interface GasOptimizedSchedulerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelTransaction"
      | "checkCondition"
      | "contractBalance"
      | "currentGasInfo"
      | "executeTransaction"
      | "getTransaction"
      | "scheduleTransaction"
      | "scheduledTxs"
      | "txCounter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TransactionCancelled"
      | "TransactionExecuted"
      | "TransactionScheduled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkCondition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentGasInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleTransaction",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduledTxs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "txCounter", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "cancelTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentGasInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduledTxs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "txCounter", data: BytesLike): Result;
}

export namespace TransactionCancelledEvent {
  export type InputTuple = [txId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [txId: bigint, owner: string];
  export interface OutputObject {
    txId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [
    txId: BigNumberish,
    executor: AddressLike,
    gasPrice: BigNumberish
  ];
  export type OutputTuple = [txId: bigint, executor: string, gasPrice: bigint];
  export interface OutputObject {
    txId: bigint;
    executor: string;
    gasPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionScheduledEvent {
  export type InputTuple = [
    txId: BigNumberish,
    owner: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    maxGasPrice: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    txId: bigint,
    owner: string,
    recipient: string,
    amount: bigint,
    maxGasPrice: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    txId: bigint;
    owner: string;
    recipient: string;
    amount: bigint;
    maxGasPrice: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GasOptimizedScheduler extends BaseContract {
  connect(runner?: ContractRunner | null): GasOptimizedScheduler;
  waitForDeployment(): Promise<this>;

  interface: GasOptimizedSchedulerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelTransaction: TypedContractMethod<
    [txId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkCondition: TypedContractMethod<
    [txId: BigNumberish],
    [
      [boolean, string, bigint] & {
        ready: boolean;
        reason: string;
        currentGas: bigint;
      }
    ],
    "view"
  >;

  contractBalance: TypedContractMethod<[], [bigint], "view">;

  currentGasInfo: TypedContractMethod<
    [],
    [[bigint, bigint] & { gasPriceWei: bigint; gasPriceGwei: bigint }],
    "view"
  >;

  executeTransaction: TypedContractMethod<
    [txId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTransaction: TypedContractMethod<
    [txId: BigNumberish],
    [GasOptimizedScheduler.ScheduledTxStructOutput],
    "view"
  >;

  scheduleTransaction: TypedContractMethod<
    [recipient: AddressLike, maxGasPrice: BigNumberish, expiry: BigNumberish],
    [bigint],
    "payable"
  >;

  scheduledTxs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, boolean, boolean] & {
        recipient: string;
        amount: bigint;
        maxGasPrice: bigint;
        expiry: bigint;
        owner: string;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  txCounter: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelTransaction"
  ): TypedContractMethod<[txId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkCondition"
  ): TypedContractMethod<
    [txId: BigNumberish],
    [
      [boolean, string, bigint] & {
        ready: boolean;
        reason: string;
        currentGas: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentGasInfo"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { gasPriceWei: bigint; gasPriceGwei: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<[txId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [txId: BigNumberish],
    [GasOptimizedScheduler.ScheduledTxStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "scheduleTransaction"
  ): TypedContractMethod<
    [recipient: AddressLike, maxGasPrice: BigNumberish, expiry: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "scheduledTxs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, boolean, boolean] & {
        recipient: string;
        amount: bigint;
        maxGasPrice: bigint;
        expiry: bigint;
        owner: string;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "txCounter"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "TransactionCancelled"
  ): TypedContractEvent<
    TransactionCancelledEvent.InputTuple,
    TransactionCancelledEvent.OutputTuple,
    TransactionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionScheduled"
  ): TypedContractEvent<
    TransactionScheduledEvent.InputTuple,
    TransactionScheduledEvent.OutputTuple,
    TransactionScheduledEvent.OutputObject
  >;

  filters: {
    "TransactionCancelled(uint256,address)": TypedContractEvent<
      TransactionCancelledEvent.InputTuple,
      TransactionCancelledEvent.OutputTuple,
      TransactionCancelledEvent.OutputObject
    >;
    TransactionCancelled: TypedContractEvent<
      TransactionCancelledEvent.InputTuple,
      TransactionCancelledEvent.OutputTuple,
      TransactionCancelledEvent.OutputObject
    >;

    "TransactionExecuted(uint256,address,uint256)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;

    "TransactionScheduled(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      TransactionScheduledEvent.InputTuple,
      TransactionScheduledEvent.OutputTuple,
      TransactionScheduledEvent.OutputObject
    >;
    TransactionScheduled: TypedContractEvent<
      TransactionScheduledEvent.InputTuple,
      TransactionScheduledEvent.OutputTuple,
      TransactionScheduledEvent.OutputObject
    >;
  };
}
